name: Create Release
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Git user
        run: |
          git config user.email "alexromantrue@gmail.com"
          git config user.name "petrovvich"
      - name: Publish package
        run: mvn -P github -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}