name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Git user
        run: |
          git config user.email "alexromantrue@gmail.com"
          git config user.name "petrovvich"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      #      - name: Publish package
      #        run: mvn --batch-mode deploy
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}